/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    BarChart: typeof import('./src/components/charts/BarChart.vue')['default']
    CodeSyncTab: typeof import('./src/components/settings/CodeSyncTab.vue')['default']
    DomainDetailTab: typeof import('./src/components/settings/DomainDetailTab.vue')['default']
    DomainManageTab: typeof import('./src/components/settings/DomainManageTab.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    EvidenceCard: typeof import('./src/components/search/EvidenceCard.vue')['default']
    ForceGraph: typeof import('./src/components/charts/ForceGraph.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    OntologyDiGraph: typeof import('./src/components/charts/OntologyDiGraph.vue')['default']
    OperatorNode: typeof import('./src/components/paradigm/OperatorNode.vue')['default']
    OperatorPalette: typeof import('./src/components/paradigm/OperatorPalette.vue')['default']
    ParamForm: typeof import('./src/components/paradigm/ParamForm.vue')['default']
    PieChart: typeof import('./src/components/charts/PieChart.vue')['default']
    PipelineFlow: typeof import('./src/components/mining/PipelineFlow.vue')['default']
    PipelineTrace: typeof import('./src/components/search/PipelineTrace.vue')['default']
    ReloadConfigTab: typeof import('./src/components/settings/ReloadConfigTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunResultPanel: typeof import('./src/components/paradigm/RunResultPanel.vue')['default']
    ServiceHealthCard: typeof import('./src/components/common/ServiceHealthCard.vue')['default']
    ServiceLogsTab: typeof import('./src/components/settings/ServiceLogsTab.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    StatsCard: typeof import('./src/components/common/StatsCard.vue')['default']
    StatusBadge: typeof import('./src/components/common/StatusBadge.vue')['default']
    SystemConfigTab: typeof import('./src/components/settings/SystemConfigTab.vue')['default']
    YamlEditor: typeof import('./src/components/common/YamlEditor.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
