package com.coremasterkb.serving.observability;

import com.coremasterkb.serving.domain.*;
import com.coremasterkb.serving.entity.ServingQueryLog;
import com.coremasterkb.serving.mapper.ServingQueryLogMapper;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.*;

/**
 * Writes a record to serving_query_logs after each search request.
 *
 * <p>Called exclusively from {@link QueryLogAspect} -- must never be injected
 * into business code. All failures are swallowed so logging never affects the
 * main response.</p>
 */
@Component
public class QueryLogService {

    private static final Logger log = LoggerFactory.getLogger(QueryLogService.class);
    private static final String FALLBACK_CHANNEL = "prod";

    private final ServingQueryLogMapper logMapper;
    private final ObjectMapper objectMapper = new ObjectMapper();

    public QueryLogService(ServingQueryLogMapper logMapper) {
        this.logMapper = logMapper;
    }

    /**
     * Record a completed (or failed) search invocation.
     *
     * @param queryId    UUID generated by the aspect
     * @param request    original search request (input)
     * @param pack       assembled context pack (output); null if pipeline threw
     * @param durationMs wall-clock time measured by the aspect
     */
    public void record(String queryId, SearchRequest request, ContextPack pack, long durationMs) {
        try {
            String domain = request.domain() != null && !request.domain().isBlank()
                    ? request.domain() : "default";
            String channel = request.channel() != null && !request.channel().isBlank()
                    ? request.channel() : FALLBACK_CHANNEL;

            ServingQueryLog entry = new ServingQueryLog();
            entry.setId(queryId);
            entry.setDomain(domain);
            entry.setChannel(channel);
            entry.setQueriedAt(Instant.now().toString());
            entry.setDurationMs((int) Math.min(durationMs, Integer.MAX_VALUE));
            entry.setQueryText(request.query());
            entry.setMetadataJson("{}");
            entry.setKeywordsJson("[]");
            entry.setEntitiesJson("[]");
            entry.setScopeJson("{}");
            entry.setResultIssuesJson("[]");
            entry.setResultItemsJson("[]");
            entry.setResultSourcesJson("[]");
            entry.setResultRelationsJson("[]");

            if (pack != null && pack.query() != null) {
                ContextQuery q = pack.query();
                entry.setIntent(q.intent());
                entry.setNormalizerSource(q.source());
                entry.setKeywordsJson(toJson(q.keywords()));
                entry.setEntitiesJson(toJson(q.entities()));
                entry.setScopeJson(toJson(q.scope()));
                entry.setReleaseId(q.releaseId());
                entry.setBuildId(q.buildId());
                entry.setSnapshotCount(q.snapshotCount());
            }

            if (pack != null) {
                List<ContextItem> items = pack.items();
                long seedCount = items.stream()
                        .filter(i -> "seed".equals(i.role()))
                        .count();
                boolean hasResult = seedCount > 0;

                entry.setResultItemCount(items.size());
                entry.setResultSeedCount((int) seedCount);
                entry.setResultHasResult(hasResult);
                entry.setResultIssuesJson(toJson(pack.issues()));
                entry.setResultItemsJson(toJson(buildItemLogs(items)));
                entry.setResultSourcesJson(toJson(buildSourceLogs(pack.sources())));
                entry.setResultRelationsJson(toJson(buildRelationLogs(pack.relations())));
            } else {
                entry.setResultHasResult(false);
            }

            logMapper.insert(entry);

        } catch (Exception e) {
            log.warn("Failed to write query log [{}]: {}", queryId, e.getMessage());
        }
    }

    // -------------------------------------------------------------------------
    // Compact serialization -- text fields excluded to keep rows small
    // -------------------------------------------------------------------------

    private List<Map<String, Object>> buildItemLogs(List<ContextItem> items) {
        List<Map<String, Object>> result = new ArrayList<>();
        for (ContextItem item : items) {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", item.id());
            m.put("kind", item.kind());
            m.put("role", item.role());
            m.put("score", item.score());
            m.put("block_type", item.blockType());
            m.put("semantic_role", item.semanticRole());
            m.put("source_id", item.sourceId());
            m.put("relation_to_seed", item.relationToSeed());
            result.add(m);
        }
        return result;
    }

    private List<Map<String, Object>> buildSourceLogs(List<SourceRef> sources) {
        List<Map<String, Object>> result = new ArrayList<>();
        for (SourceRef src : sources) {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", src.id());
            m.put("document_key", src.documentKey());
            m.put("title", src.title());
            m.put("relative_path", src.relativePath());
            result.add(m);
        }
        return result;
    }

    private List<Map<String, Object>> buildRelationLogs(List<ContextRelation> relations) {
        List<Map<String, Object>> result = new ArrayList<>();
        for (ContextRelation rel : relations) {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", rel.id());
            m.put("from_id", rel.fromId());
            m.put("to_id", rel.toId());
            m.put("relation_type", rel.relationType());
            m.put("distance", rel.distance());
            result.add(m);
        }
        return result;
    }

    private String toJson(Object obj) {
        if (obj == null) return "[]";
        try {
            return objectMapper.writeValueAsString(obj);
        } catch (JsonProcessingException e) {
            return obj instanceof java.util.Map ? "{}" : "[]";
        }
    }
}
